/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package matrodriguezpa.receiptmanager.view;

/**
 *
 * @author Juan Camilo
 */
public class MonthView extends javax.swing.JPanel {

    /**
     * Creates new form NewJPanel2
     */
    public MonthView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainTableScroll = new javax.swing.JScrollPane();
        mainTable = new javax.swing.JTable();
        mainTableHeader = new javax.swing.JToolBar();
        addProject = new javax.swing.JButton();
        addMonth = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        mainTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Expense date", "Company name", "Amount", "Expense", "Matrix", "Payment Method"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Float.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        mainTableScroll.setViewportView(mainTable);

        add(mainTableScroll, java.awt.BorderLayout.CENTER);

        mainTableHeader.setRollover(true);
        mainTableHeader.setMaximumSize(new java.awt.Dimension(150, 30));
        mainTableHeader.setMinimumSize(new java.awt.Dimension(150, 30));
        mainTableHeader.setPreferredSize(new java.awt.Dimension(150, 30));
        mainTableHeader.setRequestFocusEnabled(false);

        addProject.setBackground(new java.awt.Color(51, 102, 255));
        addProject.setForeground(new java.awt.Color(255, 255, 255));
        addProject.setText("AddProject");
        addProject.setFocusable(false);
        addProject.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        addProject.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        mainTableHeader.add(addProject);

        addMonth.setBackground(new java.awt.Color(51, 102, 255));
        addMonth.setForeground(new java.awt.Color(255, 255, 255));
        addMonth.setText("AddMonth");
        addMonth.setFocusable(false);
        addMonth.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        addMonth.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        addMonth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addMonthActionPerformed(evt);
            }
        });
        mainTableHeader.add(addMonth);

        add(mainTableHeader, java.awt.BorderLayout.PAGE_START);
    }// </editor-fold>//GEN-END:initComponents

    private void addMonthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addMonthActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addMonthActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addMonth;
    private javax.swing.JButton addProject;
    private javax.swing.JTable mainTable;
    private javax.swing.JToolBar mainTableHeader;
    private javax.swing.JScrollPane mainTableScroll;
    // End of variables declaration//GEN-END:variables
}
